language: go
go:
  - 1.6
  - 1.5.3
  - 1.4.3
  - 1.3.3

sudo: false

before_install:
  - go get golang.org/x/tools/cmd/vet
  - go version | (grep -q 'go1.[56]' || exit 0 && go get -u github.com/golang/lint/golint )
  - go get github.com/vbatts/git-validation

install: true

script:
  - go vet -x ./...
  - make .golint
  - $HOME/gopath/bin/git-validation -run DCO,short-subject -v -range ${TRAVIS_COMMIT_RANGE}
  
